// <auto-generated />
using Fan_Website.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fan_Website.Migrations.Screenshot
{
    [DbContext(typeof(ScreenshotContext))]
    [Migration("20210415215617_Screenshot")]
    partial class Screenshot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fan_Website.Models.Screenshot", b =>
                {
                    b.Property<int>("ScreenshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenshotDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenshotTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScreenshotId");

                    b.ToTable("Screenshots");

                    b.HasData(
                        new
                        {
                            ScreenshotId = 4,
                            ImagePath = "Final_Fantasy_XV_Chocobo-1.png",
                            ScreenshotDescription = "I finally managed to find a chocobo",
                            ScreenshotTitle = "Final Fantasy XV Chocobo"
                        },
                        new
                        {
                            ScreenshotId = 2,
                            ImagePath = "Final-Fantasy-VII-Remake-Sephiroth.png",
                            ScreenshotDescription = "This is my favorite game of all title",
                            ScreenshotTitle = "Sephiroth from Final Fantasy VII"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
